Repository Call-for-Code-for-Racial-Justice/Five-Fifths-Voter, pull requests merged in 2021-11, with the labels that each got.

#300 Adding PWA assets to the site
  ui/package.json
  ui/public/img/icons/android-chrome-192x192.png
  ui/public/img/icons/android-chrome-512x512.png
  ui/public/img/icons/android-chrome-maskable-192x192.png
  ui/public/img/icons/android-chrome-maskable-512x512.png
  ui/public/img/icons/apple-touch-icon-120x120.png
  ui/public/img/icons/apple-touch-icon-152x152.png
  ui/public/img/icons/apple-touch-icon-180x180.png
  ui/public/img/icons/apple-touch-icon-60x60.png
  ui/public/img/icons/apple-touch-icon-76x76.png
  ui/public/img/icons/apple-touch-icon.png
  ui/public/img/icons/favicon-16x16.png
  ui/public/img/icons/favicon-32x32.png
  ui/public/img/icons/msapplication-icon-144x144.png
  ui/public/img/icons/mstile-150x150.png
  ui/src/main.js
  ui/src/registerServiceWorker.js
  ui/tests/unit/a11y.spec.js
  ui/vue.config.js
  ui/yarn.lock
Labels: pwa

#302 adding asset link file for production application
  ui/public/.well-known/assetlinks.json
Labels: pwa

#287 Fix spanish translations
  ui/src/plugins/es.json
Labels: hacktoberfest

#304 Adding ci/cd for ui and services blue version
  .github/workflows/deployment.yml
  .gitignore
  services/blue.yml
  services/manifest-blue.yml
  ui/blue.yml
  ui/manifest-blue.yml
Labels: CI/CD
